version: '3.7'
services:

  ipam:
    # image: phpipamoprek:latest
    build: .
    container_name: oprek_phpipam
    hostname: phpIPAMLabs
    restart: unless-stopped
    ports: 
        - 80:80
    environment:
      - MYSQL_DB_HOSTNAME=oprek_maria_db
      - MYSQL_DB_USERNAME=
      - MYSQL_DB_PASSWORD=
      - MYSQL_DB_NAME=
      - MYSQL_DB_PORT=3306
    networks:
      - oprek_net
    volumes:
      - ${PWD}/logs/nginx:/var/log/nginx/

  myadmin:
    image: phpmyadmin:latest
    container_name: oprek_myadmin
    hostname: myadmin
    restart: unless-stopped
    ports:
      - 6868:80
    environment:
      - PMA_HOST=oprek_maria_db
    networks:
      - oprek_net

  db:
    image: "mariadb:10.3"
    container_name: oprek_maria_db
    hostname: db
    restart: unless-stopped
    networks:
      - oprek_net
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=200
      - --max_heap_table_size=256M
      - --max_allowed_packet=32M
      - --tmp_table_size=256M
      - --join_buffer_size=512M
      - --innodb_buffer_pool_size=4G
      - --innodb_doublewrite=OFF
      - --innodb_flush_log_at_timeout=3
      - --innodb_read_io_threads=32
      - --innodb_write_io_threads=16
      - --innodb_buffer_pool_instances=40
      - --innodb_file_format=Barracuda
      - --innodb_large_prefix=1
      - --innodb_io_capacity=5000
      - --innodb_io_capacity_max=10000
    environment:
      - MYSQL_ROOT_PASSWORD=
      - TZ=Asia/Jakarta
    volumes:
      - ${PWD}/config/mariadb:/var/lib/mysql
      - ${PWD}/logs/mariadb:/var/logs/mariadb

networks:
  oprek_net:
    external: true
